spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    generate-ddl: true
    show-sql: true
    properties:      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQL10Dialect  application:    name: shopping-cart-service
logging:  level:
    org.springframework: info