spring:
  jpa:
    database: postgresql
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping-cart
    username: postgres
    password: root123