spring: 
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    generate-ddl: false
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.H2Dialect