spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  application:
    name: shopping-cart-service
  mvc:
    static-path-pattern: "/**"
logging:
  level:
    org.springframework: info
server:
  servlet:
    context-path: /shopping-cart-service