spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: shopping-cart-service
  mvc:
    static-path-pattern: "/**"
logging:
  level:
    org.springframework: info
server:
  servlet:
    context-path: /shopping-cart-service