spring:
  profiles:
    active: h2 #This is only evaluator, to run the application directly. This would not exist in the app yml file.
  jpa:
    hibernate:
      ddl-auto: update # This is just for evaluation purpose.
    generate-ddl: true
    show-sql: true
  application:
    name: shopping-cart-service
  mvc:
    static-path-pattern: "/**"
logging:
  level:
    root: info
    org.springframework: info
server:
  servlet:
    context-path: /shopping-cart-service
